### ISSUE TITLE
Won't work

### ISSUE THREAD

**Issue by HarriBuh** [Hepolise/VolumeKeyTrackControlModule#13]
Google Pixel 7
Android 14
Rooted with Magisk 27.0
LSPosed 1.9.2

I tried using it with the official Deezer app.

What I did so far:

- Turned off battery optimization
- Selected "System Framework" as suggested
- Started Deezer, started playing a song, turned off screen

**Comment by Hepolise** [comment]
Did you reboot your phone? 

If so, can you please install debug version ([Build Artifacts.zip](https://github.com/Hepolise/VolumeKeyMusicManagerModule/files/15203668/Build.Artifacts.zip) or you can use [a build from the workflow run](https://github.com/Hepolise/VolumeKeyMusicManagerModule/actions/runs/8937148259))? Then reboot, start music, turn off the screen, try to skip songs and attach here modules logs from LSPosed.
